### ISSUE TITLE
Flask Resource Server doesn't work with Samples-js-vue repository

### ISSUE THREAD

**Issue by O-Luhishi** [okta/samples-python-flask#31]
As per the instructions in the ReadMe, the resource server needs a frontend to authenticate with. However, the VueJs frontend only works with PKCE Flow whereas the flask resource server uses the implicit flow. As a result, messages page can’t successfully fetch the data.

Is there any chance we could get the flask resource server to work with the PKCE Flow? 

Thanks!

**Comment by serhiibuniak-okta** [comment]
@O-Luhishi Could you please, provide more details? What kind of error? What does flask log to console (if logs anything)?
The thing is, flask resource server and one of frontends (vue in this case) are not connected to each other directly. Front-end is a client, which should authenticate user and check if user is authorized to get resources from server app (flask).

**Comment by O-Luhishi** [comment]
Hey @serhiibuniak-okta , thanks for the prompt reply! Apologies for not adding more info, but basically the instructions on the Flask Resource Server page says it needs a frontend as a prerequisite [here](https://github.com/okta/samples-python-flask/tree/master/resource-server#prerequisites)

Within the [Sample-JS-Vue Repo](https://github.com/okta/samples-js-vue/blob/master/okta-hosted-login/src/config.js#L15), the Frontend has a page called Messages which makes a HTTP Call to any server running on `localhost:8000/api/messages`. 

Now when I run both projects simultaneously, and I visit the `Messages` page, the flask app registers a HTTP Request like so: 
```
127.0.0.1 - - [13/Nov/2020 20:31:59] "OPTIONS /api/messages HTTP/1.1" 200 -
127.0.0.1 - - [13/Nov/2020 20:46:55] "GET /api/messages HTTP/1.1" 401 -
```

And when I inspect the browser the frontend returns: 

`GET http://localhost:8000/api/messages 401 (UNAUTHORIZED)`

And of course, the frontend, returns this page: 
```
Failed to fetch messages. Please verify the following:
You've downloaded one of our resource server examples, and it's running on port 8000.
Your resource server example is using the same Okta authorization server (issuer) that you have configured this Vue application to use.
```

The way both projects have been setup differently, because the VueJs Frontend is setup to work with PKCE Flow, so when you create an application in the Okta Dashboard it does not generate a client secret and so you can't pass it to the Flask app [here ](https://github.com/okta/samples-python-flask/blob/master/resource-server/client_secrets.json.dist#L5), which of course breaks the app at runtime. But even if you set the application in Okta to use the Implicit flow and have the VueJs frontend authenticate with it, that also doesn't work and just produces the above.

Is there any chance this resource server could be fixed to support PKCE Flow to be consumed by the VueJs Frontend?

**Comment by serhiibuniak-okta** [comment]
@O-Luhishi hi, I can confirm that it is working (I used separate virtual machine with Ubuntu 20.04 to make clean setup):
```
127.0.0.1 - - [14/Nov/2020 14:49:17] "OPTIONS /api/messages HTTP/1.1" 200 -
127.0.0.1 - - [14/Nov/2020 14:49:18] "GET /api/messages HTTP/1.1" 200 -
```
<img width="1100" alt="Screenshot 2020-11-14 at 14 55 53" src="https://user-images.githubusercontent.com/73126645/99147456-be4ca080-2689-11eb-8140-a5edc9aa1bee.png">

So, first of all, ensure you have the latest version of sample flask app: 4 days ago I made a fix to allow cross-domain requests - https://github.com/okta/samples-python-flask/pull/28/files
Next, open browser console if error still exists and show please which error message appears in console (response on network tab)

**Comment by O-Luhishi** [comment]
That's strange. I think maybe there is a difference in setup between our applications in Okta.

I followed the VueJS ReadMe which says to within my developer dashboard to create an SPA application which uses PKCE for client authentication (which doesn't provide a client secret which is used in the resource server [here](https://github.com/okta/samples-python-flask/blob/master/resource-server/client_secrets.json.dist#L5)).

I provide the client ID again to VueJS project which works, as I am able to authenticate. I then pass my Client ID to the Resource server [here](https://github.com/okta/samples-python-flask/blob/master/resource-server/client_secrets.json.dist#L5), but again it's missing the client secrets as it is not generated when I created the application to use PKCE. 

When I click messages I get the following in the console from the network tab:
`{"error": "invalid_token", "error_description": "Token required but invalid"}`

This is also how my application is setup within Okta:

![tempsnip](https://user-images.githubusercontent.com/18488979/99150925-8c3e3d00-268f-11eb-86ca-9ff022bfd26a.png)

Again, I think it's because one application is running with PKCE flow and the other with Implicit Flow. Just not sure how to get the resource server to run as PKCE.

 Edit:

I also tested it by modifying my application in Okta to also accept Implicit flow and still same result.

And I'm using the `Okta-Hosted-Login` project from the Vue Sample Project [here](https://github.com/okta/samples-js-vue/tree/master/okta-hosted-login)

**Comment by serhiibuniak-okta** [comment]
Yes, that configuration is fine. And flask app should use another application and configuration - web app with client id/secret.
What you can try: get auth header from browser when it tries to get messages:
<img width="1266" alt="Screenshot 2020-11-14 at 19 27 58" src="https://user-images.githubusercontent.com/73126645/99153164-848e9080-26af-11eb-8a82-72733dede0aa.png">
then use that auth header in the following curl command (try to query flask directly):

`curl localhost:8000/api/messages -H "Authorization: Bearer {YOUR_TOKEN}"`
Output:
`{"messages": [{"date": 1605374683.6773725, "text": "I am a robot."}, {"date": 1605371083.6773736, "text": "Hello, World!"}]}`

**Comment by O-Luhishi** [comment]
Ah I can see the issue now. I was under the impression this had to be ran off a single Okta application and configuration. Whereas when I created separate applications for the resource server and for the front-end it seemed to working perfectly fine as you said! Thanks so much for the help @serhiibuniak-okta 

Slighty tangent to the issue, but does this mean that the resource server uses implicit flow and the frontend uses PKCE? Or am I comparing apples and oranges (i.e. 2 different things)?

**Comment by serhiibuniak-okta** [comment]
@O-Luhishi Yes, it's a bit confusing, maybe it would be good to improve readme for both examples. It is better to think about these apps as distinct services. Resource-server (flask) has some resources (messages), front-end (vue, angular, etc.) authorizes user, i.e. checks if user has permissions to get resources and returns those resources. Hope, this helps. Please, let me know if there is anything confusing still.

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as it seems to be resolved. Feel free to create new issue in case of some help is needed.

**Comment by widowitz** [comment]
Dear all, dear @serhiibuniak-okta ,

I am experiencing, as of today, exactly the same issues as described on this page.

Unfortunately, I am unable to resolve it in spite of closely following (or so I thought) the instructions.

Can you maybe tell where I'm going wrong?
* create in the Okta admin panel one application, SPA, for the frontend. Select and download the Vue code. Install locally. Edit configuration in the testenv file by entering ISSUER and CLIENT_ID (from this application, obviously). Run it. It displays the frontend and ability to log in and view the profile. Messages part does not work, as expected at this step
* create a SECOND application in the Okta admin panel, this time a web application, for the backend. Download the latest Flask code from the git repository (not the one offered in the download link as that one is outdated!). Customize the client_secrets.json to match the data from the SECOND application. Run it. The Flask web server runs in the background, successfully
* however, the messages part of the frontend still shows 401-Unauthorized when trying to view the messages. To some extent, I find this natural -- since I have never linked up those two applications. 

Obviously I am not getting something... can you help? THANK YOU!!

**Comment by serhiibuniak-okta** [comment]
Hi @widowitz , thanks for posting a detailed instruction. Could you please, point me which download link is outdated?
Regarding your problem, are you able to get message by direct querying flask endpoint? i.e. via curl/postman without front-end app?

**Comment by widowitz** [comment]
Hi, thanks for the quick response. 
I tried to curl the flask endpoint (providing the bearer token), and yes -- the result is the same 401-Unauthorized error. 

On the outdated link: 
Applications - Create App Integration - OIDC - Web application - Save - Download sample app - Python Flask
brings up this link:
https://dev-67759186-admin.okta.com/api/v1/internal/apps/0oa15qd9taEdUWjT95d7/oauth/sample-app?language=python-flask

and this is pointing to some older version of the package, as one can quickly check by looking at main.py in resource-server - it is still a version without cors support.

Thank you!

**Comment by serhiibuniak-okta** [comment]
I'll investigate why link points to outdated code. Meanwhile, let's get back to the main issue. So, you've tested it on code downloaded from GitHub? Let's debug it together, could you please make few edits locally?
For example, in file `resource-server/helpers.py`, it would be good to re-raise exception to see what might be wrong in function `is_access_token_valid`.

**Comment by widowitz** [comment]
Did that, and this lead me to debugging main.py instead.

In the is_authorized function, config["issuer"] raises a key error. Because this is what config looks like:

{'web': {'token_uri': 'https://dev-67759186.okta.com/oauth2/default/v1/token', 'auth_uri': 'https://dev-67759186.okta.com/oauth2/default/v1/authorize', 'client_secret': 'Uovm_uxxxxxxxxxxxxx2OYV', 'redirect_uris': ['http://localhost:8080/authorization-code/callback'], 'issuer': 'https://dev-67759186.okta.com/oauth2/default', 'client_id': '0oa15pe80ixxxxxxxkI25d7'}}

Apparently it is not properly treating the fact that everything is nested below "web"?

**Comment by serhiibuniak-okta** [comment]
Oh, I've updated README for only of these applications and forgot to update for 2 other. Will update soon. Yes, we need to remove key `web` and make plain config like here - https://github.com/okta/samples-python-flask/tree/master/okta-hosted-login
This key 'web' was needed only for flask-oidc library.

**Comment by widowitz** [comment]
Ok, so I modified the web key accordingly. As it is still not working, looking now to debug helper.py/is_access_token_valid()

This code:
`

def is_access_token_valid(token, issuer, client_id):
    jwt_verifier = JWTVerifier(issuer, client_id, 'api://default')
    print('one')
    try:
        print('two')
        loop.run_until_complete(jwt_verifier.verify_access_token(token))
        print('three')
        return True
    except Exception as e:
        print('four')
        print(e)
        print('five')
        raise(e)
        # return False

`

now outputs:

`127.0.0.1 - - [07/Jul/2021 17:59:50] "OPTIONS /api/messages HTTP/1.1" 200 -
one
two
four
Cannot connect to host dev-67759186.okta.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')]
five
127.0.0.1 - - [07/Jul/2021 17:59:51] "GET /api/messages HTTP/1.1" 401 -
^C%  `

So some sort of SSL issue?!

Thanks. Running on a Mac, if that might be relevant...

**Comment by serhiibuniak-okta** [comment]
Oh, Mac... I have faced with this problem long time ago with Mac machine and, frankly speaking, successfully forgot about it. Could you please, try this solution https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate?
If it won't work, I'll take a look closer a bit later.

**Comment by widowitz** [comment]
Incredible!!

With deactivated environment, and from the Applications/Python folder:
` sudo . ./Install\ Certificates.command
`

and it works like a charm. 
Thank you for your help!!

**Comment by serhiibuniak-okta** [comment]
Thanks for letting us know it works. I'll update READMEs with config a bit later, thanks for pointing to that.

**Comment by widowitz** [comment]
Dear @serhiibuniak-okta ,

After some investigation and debugging/learning, it seems that the information in the post above

https://github.com/okta/samples-python-flask/issues/31#issuecomment-727254910

is outdated by now?
Specifically, I am referring to the realization that one needs to set up two separate applications, one for the frontend, and another one for the resource server.

By now, for the Python backend, it appears to me that with the usage of JWTVerifier, no separate backend application within Okta is required. Rather, I seem to be fine with just one application, the one for the Vue frontend which authenticates the user - and the Python backend with JWTVerifier just checks authenticity of the bearer token received.

The reason why I am assuming this is that I realized how in the call to JWTVerifier(issuer, client_id, 'api://default'), it does actually not matter what client_id is being passed... which makes sense, as we are just validating a self-contained JWT, aren't we. But then, the client_id of the backend is irrelevant... hence it is not needed. I confirmed by just deactivating it, still works :)

Could you kindly confirm? If I am wrong, then I am fundamentally not getting something here. If I'm correct, on the other hand, probably the existing documentation could be even further simplified...

Thank you!

**Comment by serhiibuniak-okta** [comment]
@widowitz There are 2 types of tokens: `access token` and `id token`. `client_id` is needed if anyone needs to verify `id token`. With this sample case, we're verifying `access token`, hence, `client_id` can be anything. By tech design, it is required parameter, maybe we'll need to make some changes in it.

**Comment by serhiibuniak-okta** [comment]
@widowitz okta-jwt-verifier v0.2.0 has been released. Now you can use either AccessTokenVerifier or IDTokenVerifier. Flask samples will be updated soon accordingly

**Comment by widowitz** [comment]
Serhii, I am continuously getting a Deprecation Warning -- no matter if I use JWTVerifier or IDTokenVerifier (which makes sense given that IDTokenVerifier builds on JWTVerifier).
"JWTVerifier will be deprecated soon."
Any advice how to deal with this?
Thanks!

**Comment by serhiibuniak-okta** [comment]
@widowitz As a temporary workaround, I'd suggest using something like the following:
```py
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
```
I'll remove warnings from subclasses soon.

**Comment by widowitz** [comment]
thx.

**Comment by serhiibuniak-okta** [comment]
@widowitz warnings removed, jwt-verifier v0.2.1 has been released
